title: Binjie Liao's Homepage
page-top-title: Binjie Liao（廖彬杰）
top-section-bg-text: Electric Engineering
home-subtitle: Binjie Liao&ensp;|&ensp;廖彬杰
copyright-text: '&copy; Binjie Liao 2025-2026. All Rights Reserved.'
